
puts "  +      o     +              o    "
puts "    +             o     +       +  "
puts "o          +                       "
puts "    o  +           +        +      "
puts "+        o     o       +        o  "
puts "-_-_-_-_-_-_-_,------,      o      "
puts "_-_-_-_-_-_-_-|   /\\_/\\          "
puts "-_-_-_-_-_-_-~|__( ^ .^)  +     +  "
puts "_-_-_-_-_-_-_-```  ```             "
puts "+      o         o   +       o     "
puts "    +         +                    "
puts "o        o         o      o     +  "
puts "    o           +                  "
puts "+      +     o        o      +     "
